### ISSUE TITLE
Recursion annotations not show in vertical ruler when the method is a generics method

### ISSUE THREAD

**Issue by humphreygao** [gayanper/gap-eclipse-plugins#18]
For example, the Line 14, 15:

![recursive method](https://user-images.githubusercontent.com/52394598/79100380-ecd36780-7d98-11ea-99c3-cb4382223e89.png)

When it comes to generics class like below: 
```java
public class BinarySearchTree<E extends Comparable<E>> {

    private Node root;
    private int size;

    public BinarySearchTree() {
        this.root = null;
        this.size = 0;
    }

    public void add(E e) {
        root = add(root, e);
    }

    private Node add(Node node, E e) {
        if (node == null) {
            size++;
            return new Node(e);
        }

        if (e.compareTo(node.e) < 0) {
            node.left = add(node.left, e);
        } else if (e.compareTo(node.e) > 0) {
            node.right = add(node.right, e);
        }
        return node;
    }

    private class Node {

        public E e;

        public Node left, right;

        public Node(E e) {
            this.e = e;
            left = null;
            right = null;
        }
    }

}
```
The annotations are missing too:

![recursive method in generics class](https://user-images.githubusercontent.com/52394598/79102058-8e0fed00-7d9c-11ea-8f55-605078f94906.png)

Recursive call gutter icons are shown in Intellij IDEA:

![recursive call gutter icons](https://user-images.githubusercontent.com/52394598/79102328-1bebd800-7d9d-11ea-91db-654d5f1b0f4f.png)

**Comment by gayanper** [comment]
@humphreygao sure i will have a look at it.

**Comment by gayanper** [comment]
The fix is in https://travis-ci.org/github/gayanper/gap-eclipse-plugins/builds/674307031

**Comment by humphreygao** [comment]
@gayanper It works, Thank you!

![recursive](https://user-images.githubusercontent.com/52394598/79111557-4fcff900-7daf-11ea-894e-d282a3d5c4ed.png)
